# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - winequalitytest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://winequalitytest.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d40f949e34934abcb2304d1287cd67a4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4e885540865d4a2f8879b049408dea44 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: winequalitytest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d40f949e34934abcb2304d1287cd67a4 }}/winequality:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'winequalitytest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3d9a899af95b46debf63d19bfb84e541 }}
        images: 'winequalitytest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d40f949e34934abcb2304d1287cd67a4 }}/winequality:${{ github.sha }}'